version: '3'

services:
    demo:
        image: demo:latest
        container_name: demo
        ports:
            - "6080:80/tcp"
        volumes:
            - demo_volume:/opt/app

volumes:
    demo_volume:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /volumes/demo_volume
